### ISSUE TITLE
UI improvements 

### ISSUE THREAD

**Issue by yutakahoulette-zz** [jayrbolton/anchor-hash-scroll#2]
Some issues we noticed while using this for Rally Starter: 

- If a target section is too short to reach the top of the screen, the `data-active` attr doesn't get applied to the corresponding link
- If a link is clicked before the scrolling is finished, the page jumps around
- Preferably, the `data-active` attr should be set right when the link is clicked

**Comment by jayrbolton** [comment]
Fixing this stuff :wrench:

**Comment by jayrbolton** [comment]
I fixed the items above. One other issue I didn't touch is below. I couldn't think of a simple solution to it off hand:
* if the section is short and at the bottom of the screen, and the window top cannot scroll to it, then that section wont get highlighted in the nav by scrolling. It will get highlighted when clicking the nav link, but as soon as you scroll, the nav will highlight the above section
