### ISSUE TITLE
How to use without a module bundler

### ISSUE THREAD

**Issue by GAumala** [jayrbolton/anchor-hash-scroll#5]
Hello, this project looks very useful to me, great work! 

I want to use it in a static site that I'm building. I don't use a module bundler or a package manager for dependencies. I was wondering if you have something like a CDN link that I could use in a script tag?

**Comment by jayrbolton** [comment]
Hey @GAumala, I can include distribution versions, eg. a pre-bundled version and also a minified and gzipped version that you can host on a cdn. Once I put these files in the repo, maybe you can put it on a CDN and then I can link it in the readme. I think there are free cdns for open source projects.

**Comment by GAumala** [comment]
That would be amazing! Yeah there are some free CDNs for these kind of projects. You could also use [github-pages](https://help.github.com/articles/what-is-github-pages/) since it already uses a global CDN.

**Comment by thom4parisot** [comment]
You could use https://wzrd.in/ or https://unpkg.com/ to achieve such a thing.

They browserify on the fly.

**Comment by jayrbolton** [comment]
Try this URL out:
```
https://unpkg.com/anchor-hash-scroll/dist/build.min.js
```

**Comment by webowski** [comment]
Hi, Jay! Cool and neat plugin
Is there possibility to change options when I use the CDN?
Change offset, for example

**Comment by jayrbolton** [comment]
Hi @webowski it doesn't support configuration from the CDN quite yet. I think it'd be a good feature and one I've thought about adding. I would likely be able to work on it this week or this weekend if nobody else works on it.

**Comment by jayrbolton** [comment]
@webowski I made the code changes to allow configuration with the cdn using `window.anchorHashScroll.config({offset: -99, duration: 1000})`. It's not yet updated on unpkg and I'm not yet remembering what triggers an update there. Have to run for now but will check back later.

**Comment by jayrbolton** [comment]
@webowski The updated version is live, you can include it with `<script type='text/javascript' src='//unpkg.com/anchor-hash-scroll@0.1.5/dist/build.min.js'></script>`

You can configure (and re-configure) the options at any point using `window.anchorHashScroll.config({duration, offset})`.
